### ISSUE TITLE
Question, please requesting answers

### ISSUE THREAD

**Issue by 8cyh** [abubakar-sani/anti_jamming#1]
Hello author, may I ask which version of the ns3 Gym package you are using? You mentioned it as 1.0.2, but there is no description of 1.0.2 on the official website, only something similar to 3.30? After installing, I ran a prompt on the virtual machine stating that I couldn't find the ns3 file. I don't know why. Also, I would like to ask if you are running code under Linux. Could you please provide a running tutorial? Thank you very much. My email is 3323542296@qq.com

**Comment by bunuaaxjw** [comment]
Hello, 1.0.2 is the version of ns3-gym, 3.30 is the version of ns3.

**Comment by 8cyh** [comment]
May I ask if you could explain how to install ns3-gym, or if there are tutorials available? This installation is a bit difficult. Thank you

**Comment by 8cyh** [comment]
My environment has been installed, but I don't know why it won't produce results. May I know how to use the running program？

**Comment by bunuaaxjw** [comment]
https://github.com/tkn-tub/ns3-gym 
This is ns3-gym installation

**Comment by abubakar-sani** [comment]
Thanks @bunuaaxjw for providing responses. To run the code @8cyh make sure you are in the root folder. Then run

`python antiJamming_v2.py`

This will train the agent and produce the results in the paper.

FYI I am using a linux machine with ubuntu 20.0.4.
